# Generated by Django 3.0.5 on 2021-10-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('northtravel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_north',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
