# Generated by Django 3.0.5 on 2021-10-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centraltravel', '0002_auto_20211007_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_central',
            name='image',
            field=models.ImageField(upload_to='centraltravel/media'),
        ),
    ]
