# Generated by Django 3.0.5 on 2021-10-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centraltravel', '0004_auto_20211008_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_central',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
